### ISSUE TITLE
What is `lexer.dat` and how do I make one?

### ISSUE THREAD

**Issue by maxvonhippel** [dangtunguyen/IoTSan#3]
I am having a problem [with this line](https://github.com/dangtunguyen/IoTSan/blob/master/src/edu/ksu/cis/bandera/jjjc/lexer/Lexer.java#L933) in `Lexer.java`:

    int length = s.readInt();

I am getting the error:

> Unable to read lexer.dat

And the error is thrown from that line, when I check using the stacktrace.

Can you please explain what this `lexer.dat` file is?  My best guess is that I need to generate my own `lexer.dat` file based off of the classes in the files I want to look at, and that this is where the problem lies.  My full stack trace is below.  My line numbers differ a bit from yours due to comments and minor changes but everything in my version is functionally the same.  `DPM` is just my private wrapper which is calling the IoTSan logic.

> Parsing...
java.io.IOException: Stream closed
        at java.io.BufferedInputStream.getInIfOpen(BufferedInputStream.java:159)
        at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
        at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
        at java.io.DataInputStream.readInt(DataInputStream.java:387)
        at edu.ksu.cis.bandera.jjjc.unicodepreprocessor.lexer.Lexer.<init>(Lexer.java:111)
        at edu.ksu.cis.bandera.jjjc.unicodepreprocessor.UnicodeLexer.<init>(UnicodeLexer.java:48)
        at edu.ksu.cis.bandera.jjjc.unicodepreprocessor.UnicodePreprocessor.<init>(UnicodePreprocessor.java:84)
        at edu.ksu.cis.bandera.jjjc.CompilationManager.parseFile(CompilationManager.java:745)
        at edu.ksu.cis.bandera.jjjc.CompilationManager.compile(CompilationManager.java:423)
        at edu.ksu.cis.bandera.jjjc.CompilationManager.compile(CompilationManager.java:373)
        at edu.ksu.cis.bandera.bui.GDriver.runJJJC(GDriver.java:439)
        at edu.ksu.cis.bandera.bui.GDriver.run(GDriver.java:278)
        at DPM.main.java.DPM.App.main(App.java:24)
java.lang.RuntimeException: Unable to read lexer.dat.
        at edu.ksu.cis.bandera.jjjc.unicodepreprocessor.lexer.Lexer.<init>(Lexer.java:148)
        at edu.ksu.cis.bandera.jjjc.unicodepreprocessor.UnicodeLexer.<init>(UnicodeLexer.java:48)
        at edu.ksu.cis.bandera.jjjc.unicodepreprocessor.UnicodePreprocessor.<init>(UnicodePreprocessor.java:84)
        at edu.ksu.cis.bandera.jjjc.CompilationManager.parseFile(CompilationManager.java:745)
        at edu.ksu.cis.bandera.jjjc.CompilationManager.compile(CompilationManager.java:423)
        at edu.ksu.cis.bandera.jjjc.CompilationManager.compile(CompilationManager.java:373)
        at edu.ksu.cis.bandera.bui.GDriver.runJJJC(GDriver.java:439)
        at edu.ksu.cis.bandera.bui.GDriver.run(GDriver.java:278)
        at DPM.main.java.DPM.App.main(App.java:24)
[compile] java.lang.RuntimeException: Unable to read lexer.dat.

Thank you very much for your help!

**Comment by maxvonhippel** [comment]
Update:  I'm able to partially solve this problem and the same problem with `parser.dat` using FileStreams like this:

    String parserDatPath = new File("").getAbsoluteFile() 
                                          + File.separator
					  + "src" + File.separator
					  + "main" + File.separator
					  + "resources" + File.separator
					  + "parser.dat";
    FileInputStream inparser = new FileInputStream(parserDatPath);
    DataInputStream s = new DataInputStream(
				          new BufferedInputStream(inparser));
    // read actionTable
    int length = s.readInt();

... however now I get a new error:

> at edu.ksu.cis.bandera.jjjc.parser.Parser.parse(Parser.java:4711)
at edu.ksu.cis.bandera.jjjc.CompilationManager.parseFile(CompilationManager.java:752)
at edu.ksu.cis.bandera.jjjc.CompilationManager.compile(CompilationManager.java:423)
at edu.ksu.cis.bandera.jjjc.CompilationManager.compile(CompilationManager.java:373)
at edu.ksu.cis.bandera.bui.GDriver.runJJJC(GDriver.java:439)
 at edu.ksu.cis.bandera.bui.GDriver.run(GDriver.java:278)
at DPM.main.java.DPM.App.main(App.java:24)
> [compile] edu.ksu.cis.bandera.jjjc.parser.ParserException: [1,7]                        "EOF expected.",
> Finished running JJJC.

Any help on this front would be much appreciated.  I've tried just adding a newline to the .dat file but this didn't do the trick.  I haven't tried writing `0000` or anything like that, yet.

**Comment by maxvonhippel** [comment]
Bizarrely, without any meaningful change on my part, I'm now getting a totally different error:

> Compiling: /home/mvh/projects/research/DPM/lib/SmartThings.java
Parsing...
.......................... THIS FAR ..........................
105
Exception in thread "main" java.lang.OutOfMemoryError: Java heap space
        at edu.ksu.cis.bandera.jjjc.parser.Parser.<init>(Parser.java:1028)
        at ca.mcgill.sable.laleh.java.astfix.JJCParser.<init>(JJCParser.java:43)
        at edu.ksu.cis.bandera.jjjc.CompilationManager.parseFile(CompilationManager.java:751)
        at edu.ksu.cis.bandera.jjjc.CompilationManager.compile(CompilationManager.java:423)
        at edu.ksu.cis.bandera.jjjc.CompilationManager.compile(CompilationManager.java:373)
        at edu.ksu.cis.bandera.bui.GDriver.runJJJC(GDriver.java:439)
        at edu.ksu.cis.bandera.bui.GDriver.run(GDriver.java:278)
        at DPM.main.java.DPM.App.main(App.java:24)

**Comment by dangtunguyen** [comment]
You can find the "Lexer.dat" and "Lexer.java" at "IoTSan/src/edu/ksu/cis/bandera/jjjc/lexer/". It seems your errors come from directory settings.

**Comment by maxvonhippel** [comment]
Hi @dangtunguyen , and thanks for the continued help.  Can you clarify what you mean RE directory settings?  I resolved the Java heap space and file not found errors, but am stuck again with the EOF expected error from `parser.java` ....

**Comment by dangtunguyen** [comment]
Hi Max,

1. Please make sure you include all the files (e.g., Lexer.data) in your project.
2. Install Groovy plugin on Eclipse following the instructions at https://github.com/groovy/groovy-eclipse/wiki
3. Add all libraries (.jar files) in the "IoTSan/lib" folder.

I have done these steps on both OSX and Windows 10, which all works properly without any errors.

**Comment by maxvonhippel** [comment]
Alright, I'll give it a shot.  The Eclipse plugin might have been my missing step.  Thank you!

**Comment by maxvonhippel** [comment]
Per your instructions, I did the following:

1. Downloaded and installed [Eclipse IDE for Java Developers](https://www.eclipse.org/downloads/packages/release/2018-12/r/eclipse-ide-java-developers), version `2018-12`
2. Launched with clean, new default workspace `/home/mvh/eclipse-worspace`
3. Dragged and dropped the `Install` button [here](https://marketplace.eclipse.org/marketplace-client-intro?mpc_install=321859) onto an empty workspace in Eclipse in order to install the *Groovy Development Tools* plugin
4. In the install confirmation window, selected all options including `Eclipse Groovy Development Tools (required)`, `Groovy Compiler 2.5`, `Groovy-Eclipse M2E Integration`, and clicked `Confirm >`
5. Selected `I accept the terms of the license agreement` and clicked `Finish`
6. When a popup appeared asking if I'd like to restart Eclipse to implement the changes I said yes, and Eclipse restarted
7. In Eclipse, did `Window -> Show View -> Other -> Git -> Git Repositories -> Open`
8. Closed the `Welcome` window in Eclipse
9. In the `Git Repositories` window, selected `Clone a git repository`
10. In `URI`, pasted `https://github.com/dangtunguyen/IoTSan.git`, then selected `Next >`
11. With `master` automatically pre-selected, selected `Next >`
12. Selected `clone submodules`, `Import all existing Eclipse projects after clone finishes`, and `Add project to working sets`, then clicked `Finish`
13. After about a minute the clone completed and the project showed up in the Eclipse `Package Explorer`.  At this point I get two errors in the `Description` window:
	> The constructor EmptyExpression() is not visible	GListExprTransformer.java	/IoTSan/src/edu/ksu/cis/bandera/jjjc/gparser/g2jconverter	line 205	Java Problem
	> The constructor EmptyExpression() is not visible	GListExprTransformer.java	/IoTSan/src/edu/ksu/cis/bandera/jjjc/gparser/g2jconverter	line 341	Java Problem
	
    I also get 10305 warnings, such as:
	
    > AbstractCollection is a raw type. References to generic type AbstractCollection<E> should be parameterized	RefHashTable.java	/IoTSan/src/edu/ksu/cis/bandera/abstraction/util	line 140	Java Problem
	
    And I get 5 Infos:
	
    > Unlikely argument type for equals(): SootMethod seems to be unrelated to String	PredicateImpl.java	/IoTSan/src/edu/ksu/cis/bandera/abstraction/predicate/parser	line 111	Java Problem
	> Unlikely argument type for equals(): SootMethod seems to be unrelated to String	PredicateImpl.java	/IoTSan/src/edu/ksu/cis/bandera/abstraction/predicate/parser	line 123	Java Problem
	> Unlikely argument type for equals(): String seems to be unrelated to GEventInfo	GDependentGraphBuilder.java	/IoTSan/src/edu/ksu/cis/bandera/jjjc/gparser/potentialriskscreener	line 60	Java Problem
	> Unlikely argument type for equals(): String seems to be unrelated to Name	ClassOrInterfaceAnalysis.java	/IoTSan/src/edu/ksu/cis/bandera/jjjc/analysis	line 82	Java Problem
	> Unlikely argument type for equals(): String seems to be unrelated to Name	SymbolTable.java	/IoTSan/src/edu/ksu/cis/bandera/jjjc/symboltable	line 301	Java Problem
14. Right-click on the first Warning, then click `Quick Fix`, but it says no quick fix is available
15. Right click on project name in `Package Explorer`, then click `Configure -> Build Path`
16. In file explorer, copy `groovy-2.5.5.jar` into `git/IoTSan/lib`
17. `Project -> Clean`
18. Exit and re-open Eclipse
19. Back in the build path configure window in Eclipse, `Libraries ->` then, select `groovy-3.0.0-alpha-3.jar` and click `delete`, then `add external jar` and add `groovy-2.5.5.jar` 

This worked and I was able to run the program.  Thanks!
